#ifndef CHUNK_CUMSUM_KKT_SOLVE_TRI_TILING_KEY_H
#define CHUNK_CUMSUM_KKT_SOLVE_TRI_TILING_KEY_H

#include "tiling/template_argument.h"

#define CHUNK_CUMSUM_KKT_SOLVE_TRI_BT64 1
#define CHUNK_CUMSUM_KKT_SOLVE_TRI_BT128 2
#define CHUNK_CUMSUM_KKT_SOLVE_TRI_FP16 10
#define CHUNK_CUMSUM_KKT_SOLVE_TRI_BF16 20

ASCENDC_TPL_ARGS_DECL(ChunkCumsumKktSolveTri,
    ASCENDC_TPL_DTYPE_DECL(D_T_K, CHUNK_CUMSUM_KKT_SOLVE_TRI_FP16, CHUNK_CUMSUM_KKT_SOLVE_TRI_BF16),
    ASCENDC_TPL_UINT_DECL(CHUNK_KEY, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
                          CHUNK_CUMSUM_KKT_SOLVE_TRI_BT64, CHUNK_CUMSUM_KKT_SOLVE_TRI_BT128)
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_K, CHUNK_CUMSUM_KKT_SOLVE_TRI_FP16),
        ASCENDC_TPL_UINT_SEL(CHUNK_KEY, ASCENDC_TPL_UI_LIST, CHUNK_CUMSUM_KKT_SOLVE_TRI_BT64)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_K, CHUNK_CUMSUM_KKT_SOLVE_TRI_FP16),
        ASCENDC_TPL_UINT_SEL(CHUNK_KEY, ASCENDC_TPL_UI_LIST, CHUNK_CUMSUM_KKT_SOLVE_TRI_BT128)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_K, CHUNK_CUMSUM_KKT_SOLVE_TRI_BF16),
        ASCENDC_TPL_UINT_SEL(CHUNK_KEY, ASCENDC_TPL_UI_LIST, CHUNK_CUMSUM_KKT_SOLVE_TRI_BT64)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_K, CHUNK_CUMSUM_KKT_SOLVE_TRI_BF16),
        ASCENDC_TPL_UINT_SEL(CHUNK_KEY, ASCENDC_TPL_UI_LIST, CHUNK_CUMSUM_KKT_SOLVE_TRI_BT128)
    )
);

#endif
